name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ec2-13-60-36-98.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

        

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com << 'EOF'
          cd ~/NestJS_Hello_World
          git pull origin main
          npm install
          npm run build
          pm2 restart nestjs-app || pm2 start dist/main.js --name "nestjs-app"
        EOF
