name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }}:/home/${{ secrets.EC2_USER }}/nestjs-hello-world/

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/nestjs-hello-world
          npm install
          pm2 stop all || true
          pm2 start dist/main.js --name "nestjs-hello-world"
        EOF
