name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-60-66-193.eu-north-1.compute.amazonaws.com << 'EOF'
            cd ~/nestjs-hello-world
            git pull origin main
            npm install
            pm2 restart nestjs-app
          EOF
